### ISSUE TITLE
Configuration Update

### ISSUE THREAD

**Issue by MrLever** [MrLever/VoidEngine#99]
The game needs a systematic way of managing the Lua Configurations used by engine systems and entities. 

This will be accomplished through three interdependent classes:
- The Configuration Manager
- The Configurable interface
- The Configuration Resource

### Configuration Manager
- [x] Functionality covered in #119  

### Configurable Interface
- [x] Functionality covered in #118 

### The Configuration Resource
- [x] Functionality covered in #117
